charmanager_app/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login, logout

from . import views

urlpatterns = [

    url(r'^accounts/login/$',
        login,
        name='login'),

    url(r'^accounts/logout/$',
        logout,
        name='logout'),

    url(r'^accounts/register/$',
        views.register,
        name='register'),

    url(r'^usercharacters-list/$',
        views.usercharacters_list,
        name='usercharacters-list'),

    url(r'^(?P<usercharacter_id>[0-9]+)/$',
        views.usercharacter_detail,
        name='usercharacter-detail'),

    url(r'^usercharacter-update/$',
        views.usercharacter_update,
        name='usercharacter-update'),

]

charmanager_proj/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^charmanager-app/',
        include('charmanager_app.urls', namespace="charmanager_app")),
    url(r'^admin/', include(admin.site.urls)),
]

charmanager_app/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class Skill(models.Model):

    title = models.CharField(max_length=255, unique=True, error_messages={
                             'unique': 'That skill already exists.'})
    description = models.CharField(max_length=255)

    def __str__(self):
        return self.title


AbstractUser._meta.get_field('email')._unique = True
AbstractUser._meta.get_field('email').blank = False
AbstractUser._meta.get_field('username').help_text = ''


class UserCharacter(AbstractUser):

    GENDER_CHOICES = (('M', 'Male'), ('F', 'Female'))
    SPECIALIZATION_CHOICES = (('Wr', 'Warrior'), ('Tm', 'Templar'),
                              ('As', 'Assassin'), ('Rg', 'Ranger'),
                              ('Sc', 'Sorcerer'), ('Sm', 'Spiritmaster'),
                              ('Hl', 'Healer'), ('Ch', 'Chanter'))
    skills = models.ManyToManyField(Skill)
    nickname = models.CharField(max_length=255, blank=True)
    level = models.PositiveIntegerField(default=1)
    gender = models.CharField(
        max_length=1, choices=GENDER_CHOICES)
    specialization = models.CharField(
        max_length=2, choices=SPECIALIZATION_CHOICES)
    date_edit = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.username
# Create your models here.

charmanager_app/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import UserChangeForm, UserCreationForm

from .models import UserCharacter


class UserCharacterForm(ModelForm):

    class Meta:
        model = UserCharacter
        fields = [
            'username', 'nickname', 'gender', 'level', 'specialization',
            'skills',
        ]


class UserCharacterChangeForm(UserChangeForm):

    def __init__(self, *args, **kwargs):
        super(UserCharacterChangeForm, self).__init__(*args, **kwargs)
        del self.fields['password']

    class Meta:
        model = UserCharacter
        fields = [
            'username', 'nickname', 'gender', 'level', 'specialization',
            'skills',
        ]


class UserCharacterCreationForm(UserCreationForm):

    class Meta:
        model = UserCharacter
        fields = [
            'username', 'email'
        ]


class FilterForm(ModelForm):

    class Meta:
        model = UserCharacter
        fields = (
            'specialization', 'gender',
        )

charmanager_app/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from django.contrib.auth.decorators import login_required

from .models import UserCharacter, Skill
from .forms import UserCharacterForm, UserCharacterChangeForm, \
    UserCharacterCreationForm, FilterForm
from . import settings


def register(request):
    if request.method == 'POST':
        form = UserCharacterCreationForm(request.POST)
        if form.is_valid():
            new_user = form.save()
            return HttpResponseRedirect(
                reverse(
                    'charmanager_app:usercharacters-list'
                )
            )
    else:
        form = UserCharacterCreationForm()
    return render(
        request,
        "registration/register.html",
        {
            'form': form
        }
    )


def usercharacters_list(request):

    queryset = UserCharacter.objects.all()

    # filter by spec and gender, search by username and nickname

    query_params = {}
    if request.GET.get('specialization'):
        query_params['specialization'] = request.GET['specialization']
    if request.GET.get('gender'):
        query_params['gender'] = request.GET['gender']

    search_field = request.GET[
        'search_field'
    ] if request.GET.get('search_field') else ""

    queryset = queryset.filter(
        Q(username__icontains=search_field) |
        Q(nickname__icontains=search_field),
        **query_params
    )

    # separate by 4 objects on page

    paginator = Paginator(queryset, settings.PAGINATE_COUNT)
    page = request.GET.get('page')
    try:
        usercharacters = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        usercharacters = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of
        # results.
        usercharacters = paginator.page(paginator.num_pages)

    return render(
        request,
        'charmanager_app/usercharacters_list.html',
        {
            'usercharacters': usercharacters,
            'filter_form': FilterForm,
            'paginator': paginator,
        }
    )


def usercharacter_detail(request, usercharacter_id):
    usercharacter = get_object_or_404(UserCharacter, pk=usercharacter_id)
    return render(
        request,
        'charmanager_app/usercharacter_detail.html',
        {'usercharacter': usercharacter, }
    )


@login_required()
def usercharacter_update(request):
    usercharacter = request.user
    if request.method == 'POST':
        form = UserCharacterChangeForm(
            request.POST, instance=usercharacter
        )
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(
                reverse(
                    'charmanager_app:usercharacter-detail',
                    args=(usercharacter.id,)
                )
            )
    else:
        form = UserCharacterChangeForm(instance=usercharacter)
    return render(
        request,
        'charmanager_app/usercharacter_update.html',
        {
            'form': form,
            'usercharacter': usercharacter,
        }
    )

    # Create your views here.

templates/charmanager_app/usercharacter_detail.html
Profile {{ usercharacter.username }}<br><br>

Nickname - {{ usercharacter.nickname }}<br>
Gender - {{ usercharacter.get_gender_display }}<br>
Level - {{ usercharacter.level }}<br>
Specialization - {{ usercharacter.get_specialization_display }}<br><br>
Skills:<br><br>
{% for skill in usercharacter.skills.all %}
<li>{{ skill.title }} - {{ skill.description }}</li>
{% endfor %}<br>

{% if user.is_authenticated and user == usercharacter %}

    <a href="{% url 'charmanager_app:usercharacter-update' %}">Edit</a><br><br>

{% endif %}

<a href="{% url 'charmanager_app:usercharacters-list' %}">Back to list</a>

templates/charmanager_app/usercharacter_update.html
Your profile<br>

<form action="{% url 'charmanager_app:usercharacter-update' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" /><br><br>

</form>

<a href="{% url 'charmanager_app:usercharacters-list' %}">Back to list</a>

templates/charmanager_app/usercharacters_list.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'charmanager_app/style.css' %}" />

<form action="{% url 'charmanager_app:usercharacters-list' %}" method="get" >
    <h2>Specialization {{ filter_form.specialization }} Gender {{ filter_form.gender }}</h2>
    <input type="text" name="search_field" value="">
    <button>search</button>
</form>

<h1>UserCharacters</h1>

{% for usercharacter in usercharacters %}

    {# Each "usercharacter" is a UserCharacter model object. #}
    <li><a href="{% url 'charmanager_app:usercharacter-detail' usercharacter.id %}">{{ usercharacter.username }} {{ usercharacter.nickname }} ({{ usercharacter.get_specialization_display }} {{ usercharacter.gender }})</a></li>

{% endfor %}<br>

<div class="pagination">
    <span class="step-links">
        {% if usercharacters.has_previous %}
            <a href="?page={{ usercharacters.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ usercharacters.number }} of {{ usercharacters.paginator.num_pages }}.
        </span>

        {% if usercharacters.has_next %}
            <a href="?page={{ usercharacters.next_page_number }}">next</a>
        {% endif %}
    </span>
</div>
<br>

{% if request.user.is_authenticated %}

Logged as {{ request.user }}

    <a href="{% url 'charmanager_app:logout' %}">logout</a>

{% else %}

You are not logged

    <a href="{% url 'charmanager_app:login' %}">Login</a>
    <a href="{% url 'charmanager_app:register' %}">Registration</a>

{% endif %}

templates/charmanager_app/view_all_usercharacters.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'charmanager_app/style.css' %}" />

<form action="{% url 'charmanager_app:view-all-usercharacters' %}" method="get" >
    <h2>Specialization {{ filter_form.specialization }} Gender {{ filter_form.gender }}</h2>
    <input type="text" name="search_field" value="">
    <button>search</button>
</form>

<h1>UserCharacters</h1>
{% for usercharacter in usercharacters %}
    {# Each "usercharacter" is a UserCharacter model object. #}
    <li><a href="{% url 'charmanager_app:usercharacter-detail' usercharacter.id %}">{{ usercharacter.username }} {{ usercharacter.nickname }} ({{ usercharacter.get_specialization_display }} {{ usercharacter.gender }})</a></li>

{% endfor %}
<br>

<div class="pagination">
    <span class="step-links">
        {% if usercharacters.has_previous %}
            <a href="?page={{ usercharacters.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ usercharacters.number }} of {{ usercharacters.paginator.num_pages }}.
        </span>

        {% if usercharacters.has_next %}
            <a href="?page={{ usercharacters.next_page_number }}">next</a>
        {% endif %}
    </span>
</div>
<br>


<a href="{% url 'charmanager_app:register' %}">Registration</a><br>

<a href="{% url 'charmanager_app:logout' %}">Logout</a>